version: 0.1
phases:
  install:
   commands:
    - npm install -g serverless
    - npm install
  build:
   commands:
    - serverless deploy --stage dev | tee deploy.out
  post_build:
   commands:
    - npm test


