# NOTE: DynamoDB Serverless Configuration

Resources:
  GeneralLedger:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: invoiceId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: invoiceId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        # ReadCapacityUnits: ${self:custom.tableThroughput}
        # WriteCapacityUnits: ${self:custom.tableThroughput}
        BillingMode: PAY_PER_REQUEST